name: Waka Readme

on:
  schedule:
    - cron: '00 20 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: txtxj/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "auto update waka time readme"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_LAST_7_DAY_CODE_TIME: "True"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          
          
